name: Analyze
description: Analyzes the code coverage results and scans the code using CodeQL
inputs:
  reportPath:
    description: The path to the cobertura coverage file.
    required: true
  category:
    description: A unique moniker that identifies a specific portion of the mono repo
    required: true
runs:
  using: composite
  steps:
    - name: Copy Code Coverage
      shell: pwsh
      run: |
        New-Item -ItemType 'directory' -Path '${{ runner.temp }}/codecoverage/' | Out-Null
        Copy-Item '${{ inputs.reportPath }}' -Destination '${{ runner.temp }}/codecoverage/'

    - name: Upload Code Coverage Report
      uses: actions/upload-artifact@v2.2.3
      with:
        name: Coverage
        path: ${{ runner.temp }}/codecoverage

    - name: Codecov Upload
      uses: codecov/codecov-action@v2.1.0
      with:
        files: ${{ runner.temp }}/codecoverage/coverage.cobertura.xml
        flags: ${{ inputs.category }}
        fail_ci_if_error: true

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1
      with:
        category: ${{ inputs.category }}
