name: Sweetener.Linq PR

on:
  pull_request:
    branches: [ main ]
    paths:
    - .github/actions/**
    - .github/workflows/sweetener.linq-pr.yml
    - global.json
    - NuGet.config
    - src/*
    - src/Core/*
    - src/Core/Sweetener.Linq/**
    - src/Shared/**

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    permissions:
      security-events: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        uses: ./.github/actions/dotnet-test
        with:
          project: Sweetener.Linq
          solution: Core
          resultsDirectory: ${{ runner.temp }}/TestResults

      - name: Analyze
        uses: ./.github/actions/analyze
        with:
          reportPath: ${{ runner.temp }}/TestResults/*/coverage.cobertura.xml
          category: Sweetener.Linq

  package:
    name: Package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Package
        uses: ./.github/actions/dotnet-pack
        with:
          project: Sweetener.Linq
          solution: Core
          buildConfiguration: Release
          pullRequestNumber: ${{ github.event.pull_request.number }}
